# Generated by Django 5.1.5 on 2025-02-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("has_artifact", models.BooleanField(default=False)),
                (
                    "artifact_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("artifact_content", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
